version: "3.9"
services:
  lambda:
    depends_on:
      - mongo
    build: .
    ports:
      - "9000:8080"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/?authMechanism=DEFAULT
  mongo:
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db