version: "3.9"
services:
  ui:
    depends_on:
      - sam
    image: node:17.9.0
    volumes:
      - ./spa:/home/node/app
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    command: "npm start"
  sam:
    depends_on:
      - dynamodb
    build: ./lambda
    working_dir: /c/workspace/todo/lambda
    volumes:
      - ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
      - ./lambda:/c/workspace/todo/lambda
    ports:
      - "8080:3000"
    command: local start-api --container-host host.docker.internal --host 0.0.0.0 --docker-network todo_default -l /dev/stdout
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: 'amazon/dynamodb-local:1.18.0'
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb/data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
